spring:
  application:
    name: server

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/idealized?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: false
    baseline-on-migrate: true
server:
  port: 8080